### PR TITLE
Add getMonetaryUnit function

### PR DESCRIPTION
**Pull request by provsalt**
This adds getMoneyUnit function to the api

### CODE REVIEW

**Comment by Ifera** [comment]
Not needed since you can just do `ParoxityEcon::$MONETARY_UNIT`

**Comment by SOF3** [comment]
It is a bad idea to expose API through static variables.

**Comment by SOF3** [comment]
In fact, using static variables is in general a bad idea.

**Comment by Ifera** [comment]
Alright, I have some other stuff planned, will add this too ig..

**Pull request closed without merging**
